### PR TITLE
Add codemill task result

### LINKED ISSUE #1: Scrape public data from a website and to store it as JSON file
**Tech:** #node #request #cheerio #geocoding

**Details:** https://github.com/FedericoElles/codemill/tree/master/waldorf_kindergarten_de

### PR DESCRIPTION
**Pull request by jniebuhr**
codemill-id-56e7a9df2178f7030051c4e4 fixes #1

### CODE REVIEW

**Comment by jniebuhr** [comment]
Cheerio somehow didn't manage to find the sibling elements when using something like element.next('.city')
That's why I have just used element.next()

**Comment by FedericoElles** [comment]
Very nice code

**Comment by jniebuhr** [comment]
I think you have to mark this somewhere in codemill. It doesn't show up as merged

**Comment by FedericoElles** [comment]
I didn't found a button so I asked the codemill support for help.

**Comment by CodeMillApp** [comment]
We're on it.

**Comment by CodeMillApp** [comment]
Right... OK, here's from our log files, a Paypal failure:

```
The receiver {email rendered here in the origin} does not accept payments in this Currency
```

So, @jniebuhr I'm sorry but we didn't anticipate such a situation. Can you be so kind to set up your Paypal account to accept USD?

**Comment by CodeMillApp** [comment]
@jniebuhr please have a look at the answer to [this StackOverflow question](http://stackoverflow.com/questions/16239138/the-receiver-does-not-accept-payments-in-this-currency)

**Comment by jniebuhr** [comment]
@CodeMillApp added the currency :)

**Comment by CodeMillApp** [comment]
Thanks @jniebuhr! Now I have to ask you and @FedericoElles for something. I can now issue a "fake" merge process on my end and then the payment will be processed and the task status will change and each of you will also get nice emails from the system :) thing is - it will take me several hours before I can do it. 

So, any chance @jniebuhr can send a "stub" PR containing the original pull-request-string which is `codemill-id-56e7a9df2178f7030051c4e4 fixes #1` and @FedericoElles can then merge it just to fire up the trigger?

If it's OK with both of you then please do. If not, I'll do it on my end, no harm done ;-)

**Comment by jniebuhr** [comment]
i opened #3

**Pull request merged**
